id = "powerschool"
name = "PowerSchool"
version = "0.0.1"
schema_version = 1
authors = ["Caleb Frederickson"]
description = "PS-HTML including TLIST_SQL syntax highlighting for PowerSchool customizations"
repository = "https://github.com/Stroniax/zed-powerschool"

snippets = ["./snippets/powerschool html.json"]

[grammars.pshtml]
repository = "https://github.com/Stroniax/tree-sitter-pshtml"
rev = "d4bd02d2327880dd2fb9512009bf5669cd266e75"
