id = "powerschool"
name = "PowerSchool"
version = "0.0.1"
schema_version = 1
authors = ["Caleb Frederickson"]
description = "PS-HTML including TLIST_SQL syntax highlighting for PowerSchool customizations"
repository = "https://github.com/Stroniax/zed-powerschool"

[grammars.pshtml]
repository = "https://github.com/Stroniax/tree-sitter-pshtml"
rev = "6aff00cd12c2a3c6972ada09c3877cb7f9c6c50e"
